#Requires -Version 5.1
<#
.SYNOPSIS
    Sends personalized escalation emails to managers using the output from Invoke-SPDeltaCertEscalate.
.DESCRIPTION
    Reads the _email-routing.csv generated by Invoke-SPDeltaCertEscalate -EmailHtmlManagers and sends
    each manager their personalized HTML escalation report via SMTP.

    This is the second half of the escalation pipeline:

        Step 1: Invoke-SPDeltaCertEscalate -EmailHtmlManagers
                Generates tiered HTML files and a _email-routing.csv that maps each manager to
                their personalized HTML file, organized by escalation level (level2 = direct manager,
                level3 = director, level4+ = VP/SVP).

        Step 2: Invoke-SPEscalationMailer (this script)
                Reads _email-routing.csv, loads each referenced HTML file, and sends it via SMTP
                to the manager's email address. Logs every send/skip/failure to _send-log.csv.

    The HTML files produced by the escalation step are already email-friendly: inline CSS, no
    external resources, no JavaScript. They render correctly in Outlook, Gmail, and Apple Mail.

    SMTP configuration is resolved in priority order:
        1. Explicit parameters (-SmtpServer, -SmtpPort, -From, -UseSsl)
        2. Notification.Smtp section in settings.json
        3. Error if neither provides a server and from address

    This script intentionally loads only SP.Core (for config and logging). It does not require
    SP.Api, SP.Audit, or SP.DeltaCert -- it is a pure file-I/O + SMTP delivery tool.
.PARAMETER RoutingCsvPath
    Explicit path to the _email-routing.csv file. When provided, the script uses this file
    directly without searching for timestamped run folders.
.PARAMETER EscalationDir
    Base directory to search for the most recent _email-routing.csv. The script finds the
    latest timestamped subfolder and looks for _email-routing.csv inside it. Typically the
    escalation-managers directory under DeltaCert.OutputPath.
.PARAMETER SmtpServer
    SMTP server hostname. Overrides Notification.Smtp.Server in settings.json.
.PARAMETER SmtpPort
    SMTP server port. Default: 587. Overrides Notification.Smtp.Port in settings.json.
.PARAMETER From
    Sender email address. Overrides Notification.Smtp.From in settings.json.
.PARAMETER UseSsl
    Use SSL/TLS for the SMTP connection. Overrides Notification.Smtp.UseSsl in settings.json.
.PARAMETER Credential
    PSCredential for SMTP authentication. When provided, passed directly to Send-MailMessage.
.PARAMETER Subject
    Email subject line. Default: 'Action Required: Pending Attestation Review'.
.PARAMETER SubjectPrefix
    Text prepended to the subject line, e.g. "[IAM]". When specified, the final subject
    becomes "$SubjectPrefix $Subject".
.PARAMETER Levels
    Filter to send only to specific escalation levels. Valid values: 'all', '2', '3', '4',
    '5', 'no-manager'. When omitted, all rows in the routing CSV are processed.
.PARAMETER SkipAllOutstanding
    When set, excludes the 'all' row (all-outstanding.html) from the send list. The
    all-outstanding report is a consolidated view of every late reviewer; some teams prefer
    to send only the per-manager views.
.PARAMETER ConfigPath
    Path to settings.json. Defaults to ..\Config\settings.json relative to this script.
.PARAMETER Help
    Display full comment-based help and exit.
.EXAMPLE
    # Step 1: Generate escalation output
    .\Scripts\Invoke-SPDeltaCertEscalate.ps1 -CampaignNameContains 'Daily' -DaysBack 1 -Status ACTIVE -WhatIf -EmailHtmlManagers -MaxEscalationLevels 3 -Token $token

    # Step 2: Preview what would be sent
    .\Scripts\Invoke-SPEscalationMailer.ps1 -WhatIf

    # Step 3: Send level 2 managers only
    .\Scripts\Invoke-SPEscalationMailer.ps1 -Levels 2

    # Step 4: Send all levels
    .\Scripts\Invoke-SPEscalationMailer.ps1

    # Step 5: Send with explicit SMTP
    .\Scripts\Invoke-SPEscalationMailer.ps1 -SmtpServer smtp.company.com -From governance@company.com -UseSsl
.NOTES
    Script:  Invoke-SPEscalationMailer.ps1
    Version: 1.0.0
    Exit codes:
        0 = All emails sent successfully (or WhatIf)
        1 = Some emails failed (partial success)
        2 = Parameter error
        4 = Configuration error (SMTP not configured)
        5 = No routing CSV found
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    # Input source
    [Parameter()] [string]$RoutingCsvPath,
    [Parameter()] [string]$EscalationDir,

    # SMTP config (overrides settings.json)
    [Parameter()] [string]$SmtpServer,
    [Parameter()] [int]$SmtpPort = 587,
    [Parameter()] [string]$From,
    [Parameter()] [switch]$UseSsl,
    [Parameter()] [PSCredential]$Credential,

    # Email content
    [Parameter()] [string]$Subject = 'Action Required: Pending Attestation Review',
    [Parameter()] [string]$SubjectPrefix,

    # Filtering
    [Parameter()] [ValidateSet('all','2','3','4','5','no-manager')]
    [string[]]$Levels,
    [Parameter()] [switch]$SkipAllOutstanding,

    # Standard
    [Parameter()] [string]$ConfigPath,
    [Parameter()] [Alias('?')] [switch]$Help
)

Set-StrictMode -Version 1
$ErrorActionPreference = 'Stop'

if ($Help) {
    Get-Help $MyInvocation.MyCommand.Path -Detailed
    return
}

#region Module Load

$scriptRoot = $PSScriptRoot
if (-not $scriptRoot) {
    $scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
}

$toolkitRoot = Split-Path -Parent $scriptRoot

# Only SP.Core is needed -- this script does file I/O + SMTP, no ISC API calls
$coreModulePath = Join-Path $toolkitRoot 'Modules\SP.Core\SP.Core.psd1'

if (Test-Path $coreModulePath) {
    Import-Module $coreModulePath -Force -ErrorAction Stop -DisableNameChecking
}
else {
    $moduleDir = Split-Path -Parent $coreModulePath
    $psm1Files = Get-ChildItem -Path $moduleDir -Filter '*.psm1' -ErrorAction SilentlyContinue
    if ($psm1Files) {
        foreach ($psm1 in $psm1Files) {
            Import-Module $psm1.FullName -Force -ErrorAction SilentlyContinue -DisableNameChecking
        }
    }
    else {
        Write-Host "ERROR: Required module 'SP.Core' not found at: $coreModulePath" -ForegroundColor Red
        exit 2
    }
}

#endregion

#region Setup

Write-Host ''
Write-Host '  SailPoint ISC Governance Toolkit' -ForegroundColor Cyan
Write-Host '  Escalation Mailer' -ForegroundColor Cyan
Write-Host ''

# Resolve config path
if (-not $ConfigPath) {
    $ConfigPath = Resolve-SPConfigPath -ToolkitRoot $toolkitRoot
}

# Initialize logging (best-effort)
try {
    Initialize-SPLogging -ErrorAction SilentlyContinue
}
catch { }

# Load configuration
$config = $null
try {
    $config = Get-SPConfig -ConfigPath $ConfigPath
}
catch {
    Write-Host "ERROR: Failed to load configuration from '$ConfigPath': $($_.Exception.Message)" -ForegroundColor Red
    exit 4
}

# Re-initialize logging with loaded config
try {
    Initialize-SPLogging -Force -ErrorAction SilentlyContinue
}
catch { }

Write-SPLog -Message "Invoke-SPEscalationMailer started" `
    -Severity INFO -Component 'Invoke-SPEscalationMailer' -Action 'Start'

#endregion

#region Step 1: Locate the routing CSV

$routingCsvPath = $null
$baseDir = $null

if (-not [string]::IsNullOrWhiteSpace($RoutingCsvPath)) {
    # Explicit path provided
    if (-not (Test-Path $RoutingCsvPath)) {
        Write-Host "ERROR: Routing CSV not found at: $RoutingCsvPath" -ForegroundColor Red
        exit 5
    }
    $routingCsvPath = (Resolve-Path $RoutingCsvPath).Path
    $baseDir = Split-Path -Parent $routingCsvPath
}
else {
    # Determine escalation-managers base directory
    $searchBase = $null

    if (-not [string]::IsNullOrWhiteSpace($EscalationDir)) {
        $searchBase = $EscalationDir
    }
    else {
        # Derive from config: DeltaCert.OutputPath + escalation-managers
        $deltaCertOutputPath = '.\DeltaCert'
        if ($null -ne $config -and
            $config.PSObject.Properties.Name -contains 'DeltaCert' -and
            $config.DeltaCert.PSObject.Properties.Name -contains 'OutputPath' -and
            -not [string]::IsNullOrWhiteSpace($config.DeltaCert.OutputPath)) {
            $deltaCertOutputPath = $config.DeltaCert.OutputPath
        }
        if (-not [System.IO.Path]::IsPathRooted($deltaCertOutputPath)) {
            $deltaCertOutputPath = [System.IO.Path]::GetFullPath(
                (Join-Path $toolkitRoot $deltaCertOutputPath.TrimStart('.\').TrimStart('./'))
            )
        }
        $searchBase = Join-Path $deltaCertOutputPath 'escalation-managers'
    }

    if (-not (Test-Path $searchBase)) {
        Write-Host "ERROR: Escalation managers directory not found: $searchBase" -ForegroundColor Red
        Write-Host "  Run Invoke-SPDeltaCertEscalate -EmailHtmlManagers first to generate escalation output." -ForegroundColor Yellow
        exit 5
    }

    # Find the most recent timestamped subfolder containing _email-routing.csv
    $timestampedDirs = Get-ChildItem -Path $searchBase -Directory |
        Sort-Object Name -Descending

    $found = $false
    foreach ($dir in $timestampedDirs) {
        $candidatePath = Join-Path $dir.FullName '_email-routing.csv'
        if (Test-Path $candidatePath) {
            $routingCsvPath = $candidatePath
            $baseDir = $dir.FullName
            $found = $true
            break
        }
    }

    if (-not $found) {
        Write-Host "ERROR: No _email-routing.csv found in any subfolder of: $searchBase" -ForegroundColor Red
        Write-Host "  Run Invoke-SPDeltaCertEscalate -EmailHtmlManagers first to generate escalation output." -ForegroundColor Yellow
        exit 5
    }
}

Write-Host "  Routing CSV: $routingCsvPath" -ForegroundColor DarkGray
Write-Host "  Base dir:    $baseDir" -ForegroundColor DarkGray
Write-Host ''

#endregion

#region Step 2: Read the CSV

$routing = @(Import-Csv $routingCsvPath)

if ($routing.Count -eq 0) {
    Write-Host "  No rows found in routing CSV. Nothing to send." -ForegroundColor Yellow
    Write-SPLog -Message "Routing CSV is empty: $routingCsvPath" `
        -Severity WARN -Component 'Invoke-SPEscalationMailer' -Action 'ReadCsv'
    exit 0
}

Write-Host "  Loaded $($routing.Count) routing row(s)." -ForegroundColor Green

#endregion

#region Step 3: Resolve SMTP settings

# Priority: explicit params > Notification.Smtp in settings.json > error
$effectiveSmtpServer = $SmtpServer
$effectiveSmtpPort   = $SmtpPort
$effectiveFrom       = $From
$effectiveUseSsl     = $UseSsl.IsPresent
$smtpSource          = 'Parameter'

# If explicit params not provided, fall back to config
if ([string]::IsNullOrWhiteSpace($effectiveSmtpServer) -or [string]::IsNullOrWhiteSpace($effectiveFrom)) {
    $notifSmtp = $null
    if ($null -ne $config -and
        $config.PSObject.Properties.Name -contains 'Notification' -and
        $config.Notification.PSObject.Properties.Name -contains 'Smtp') {
        $notifSmtp = $config.Notification.Smtp
    }

    if ($null -ne $notifSmtp) {
        if ([string]::IsNullOrWhiteSpace($effectiveSmtpServer) -and
            $notifSmtp.PSObject.Properties.Name -contains 'Server' -and
            -not [string]::IsNullOrWhiteSpace($notifSmtp.Server)) {
            $effectiveSmtpServer = $notifSmtp.Server
            $smtpSource = 'Notification.Smtp'
        }
        if ($SmtpPort -eq 587 -and
            $notifSmtp.PSObject.Properties.Name -contains 'Port' -and
            $null -ne $notifSmtp.Port) {
            $effectiveSmtpPort = [int]$notifSmtp.Port
        }
        if ([string]::IsNullOrWhiteSpace($effectiveFrom) -and
            $notifSmtp.PSObject.Properties.Name -contains 'From' -and
            -not [string]::IsNullOrWhiteSpace($notifSmtp.From)) {
            $effectiveFrom = $notifSmtp.From
        }
        if (-not $UseSsl.IsPresent -and
            $notifSmtp.PSObject.Properties.Name -contains 'UseSsl') {
            $effectiveUseSsl = $notifSmtp.UseSsl -eq $true
        }
    }
}

# Validate SMTP config -- only required when not in WhatIf mode
if ($WhatIfPreference -ne $true) {
    if ([string]::IsNullOrWhiteSpace($effectiveSmtpServer)) {
        Write-Host "ERROR: No SMTP server configured. Provide -SmtpServer or set Notification.Smtp.Server in settings.json." -ForegroundColor Red
        exit 4
    }
    if ([string]::IsNullOrWhiteSpace($effectiveFrom)) {
        Write-Host "ERROR: No sender address configured. Provide -From or set Notification.Smtp.From in settings.json." -ForegroundColor Red
        exit 4
    }
}

Write-Host "  SMTP Server: $effectiveSmtpServer (source: $smtpSource)" -ForegroundColor DarkGray
Write-Host "  SMTP Port:   $effectiveSmtpPort" -ForegroundColor DarkGray
Write-Host "  From:        $effectiveFrom" -ForegroundColor DarkGray
Write-Host "  UseSsl:      $effectiveUseSsl" -ForegroundColor DarkGray
Write-Host ''

#endregion

#region Step 4: Filter rows

$filteredRows = [System.Collections.Generic.List[object]]::new()

foreach ($row in $routing) {
    $rowLevel = [string]$row.Level

    # Skip rows with empty ManagerEmail (no-manager rows) unless explicitly requested
    if ([string]::IsNullOrWhiteSpace($row.ManagerEmail)) {
        # Allow no-manager rows through only if -Levels explicitly includes 'no-manager'
        # Allow 'all' rows through only if not skipped
        if ($rowLevel -eq 'all' -and -not $SkipAllOutstanding) {
            # The all-outstanding row has no ManagerEmail -- skip it since there is no recipient
            # (it is a consolidated report, not addressed to a specific manager)
            continue
        }
        if ($rowLevel -eq 'no-manager') {
            if ($null -ne $Levels -and $Levels -contains 'no-manager') {
                # Explicitly requested, but still no email to send to
                continue
            }
        }
        continue
    }

    # Apply -Levels filter
    if ($null -ne $Levels -and $Levels.Count -gt 0) {
        if ($rowLevel -notin $Levels) {
            continue
        }
    }

    # Apply -SkipAllOutstanding filter
    if ($SkipAllOutstanding -and $rowLevel -eq 'all') {
        continue
    }

    $filteredRows.Add($row)
}

if ($filteredRows.Count -eq 0) {
    Write-Host "  No qualifying rows after filtering. Nothing to send." -ForegroundColor Yellow
    if ($null -ne $Levels) {
        Write-Host "  Levels filter: $($Levels -join ', ')" -ForegroundColor DarkGray
    }
    Write-SPLog -Message "No qualifying rows after filtering (Levels=$($Levels -join ','), SkipAllOutstanding=$SkipAllOutstanding)" `
        -Severity WARN -Component 'Invoke-SPEscalationMailer' -Action 'Filter'
    exit 0
}

Write-Host "  $($filteredRows.Count) email(s) to send (filtered from $($routing.Count) total row(s))." -ForegroundColor Green
Write-Host ''

#endregion

#region Step 5: Build subject line

$emailSubject = if (-not [string]::IsNullOrWhiteSpace($SubjectPrefix)) {
    "$SubjectPrefix $Subject"
}
else {
    $Subject
}

#endregion

#region Step 6: WhatIf mode

if ($WhatIfPreference -eq $true) {
    Write-Host '  [WhatIf] Dry-run mode -- no emails will be sent.' -ForegroundColor Yellow
    Write-Host ''

    foreach ($row in $filteredRows) {
        $reviewerCount = if ($null -ne $row.ReviewerCount) { $row.ReviewerCount } else { '?' }
        Write-Host "  WhatIf: Would send to $($row.ManagerEmail) (level$($row.Level), $reviewerCount reviewer(s)) -- $($row.HtmlFile)" -ForegroundColor Cyan
    }

    Write-Host ''
    $serverLabel = if (-not [string]::IsNullOrWhiteSpace($effectiveSmtpServer)) { $effectiveSmtpServer } else { '(not configured)' }
    $portLabel = $effectiveSmtpPort
    Write-Host "  WhatIf: $($filteredRows.Count) email(s) would be sent via $($serverLabel):$($portLabel)" -ForegroundColor Yellow
    Write-Host "  WhatIf: Subject: $emailSubject" -ForegroundColor DarkGray
    Write-Host ''

    Write-SPLog -Message "WhatIf: $($filteredRows.Count) email(s) would be sent" `
        -Severity INFO -Component 'Invoke-SPEscalationMailer' -Action 'WhatIf'
    exit 0
}

#endregion

#region Step 7: Send emails

$sendLog = [System.Collections.Generic.List[object]]::new()
$sentCount   = 0
$failedCount = 0
$skippedCount = 0

foreach ($row in $filteredRows) {
    $rowLevel      = [string]$row.Level
    $managerEmail  = [string]$row.ManagerEmail
    $managerName   = [string]$row.ManagerName
    $htmlFile      = [string]$row.HtmlFile
    $reviewerCount = if ($null -ne $row.ReviewerCount) { $row.ReviewerCount } else { '?' }
    $timestamp     = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

    # Resolve the HTML file path relative to the base directory
    $htmlFilePath = Join-Path $baseDir $htmlFile
    if (-not (Test-Path $htmlFilePath)) {
        $errorMsg = "HTML file not found: $htmlFilePath"
        Write-Host "  FAILED: $managerEmail (level$rowLevel) -- $errorMsg" -ForegroundColor Red
        Write-SPLog -Message "Send failed for $($managerEmail): $errorMsg" `
            -Severity WARN -Component 'Invoke-SPEscalationMailer' -Action 'Send'
        $sendLog.Add([PSCustomObject]@{
            Timestamp    = $timestamp
            Level        = $rowLevel
            ManagerEmail = $managerEmail
            ManagerName  = $managerName
            HtmlFile     = $htmlFile
            Status       = 'Failed'
            Error        = $errorMsg
        })
        $failedCount++
        continue
    }

    # Read the HTML body
    $htmlBody = $null
    try {
        $htmlBody = Get-Content -LiteralPath $htmlFilePath -Raw -Encoding UTF8
    }
    catch {
        $errorMsg = "Failed to read HTML file: $($_.Exception.Message)"
        Write-Host "  FAILED: $managerEmail (level$rowLevel) -- $errorMsg" -ForegroundColor Red
        Write-SPLog -Message "Send failed for $($managerEmail): $errorMsg" `
            -Severity WARN -Component 'Invoke-SPEscalationMailer' -Action 'Send'
        $sendLog.Add([PSCustomObject]@{
            Timestamp    = $timestamp
            Level        = $rowLevel
            ManagerEmail = $managerEmail
            ManagerName  = $managerName
            HtmlFile     = $htmlFile
            Status       = 'Failed'
            Error        = $errorMsg
        })
        $failedCount++
        continue
    }

    # Build Send-MailMessage parameters
    $mailParams = @{
        To         = $managerEmail
        From       = $effectiveFrom
        Subject    = $emailSubject
        Body       = $htmlBody
        BodyAsHtml = $true
        SmtpServer = $effectiveSmtpServer
        Port       = $effectiveSmtpPort
    }
    if ($effectiveUseSsl) { $mailParams['UseSsl'] = $true }
    if ($Credential) { $mailParams['Credential'] = $Credential }

    # Send -- belt-and-suspenders gate: ShouldProcess returns $false under -WhatIf, so even if the
    # Step-6 early-exit (which already simulates + exits in WhatIf mode) is ever changed, no mail can
    # be sent OR logged as Sent while in WhatIf/simulate mode. Sending only happens when NOT -WhatIf.
    try {
        if (-not $PSCmdlet.ShouldProcess($managerEmail, 'Send escalation email')) { continue }
        Send-MailMessage @mailParams
        Write-Host "  Sent to $managerEmail (level$rowLevel, $reviewerCount reviewer(s)) -- $htmlFile" -ForegroundColor Green
        Write-SPLog -Message "Email sent to $managerEmail (level$rowLevel, $reviewerCount reviewer(s), file=$htmlFile)" `
            -Severity INFO -Component 'Invoke-SPEscalationMailer' -Action 'Send'
        $sendLog.Add([PSCustomObject]@{
            Timestamp    = $timestamp
            Level        = $rowLevel
            ManagerEmail = $managerEmail
            ManagerName  = $managerName
            HtmlFile     = $htmlFile
            Status       = 'Sent'
            Error        = ''
        })
        $sentCount++
    }
    catch {
        $errorMsg = $_.Exception.Message
        Write-Host "  FAILED: $managerEmail (level$rowLevel) -- $errorMsg" -ForegroundColor Red
        Write-SPLog -Message "Send failed for $($managerEmail): $errorMsg" `
            -Severity ERROR -Component 'Invoke-SPEscalationMailer' -Action 'Send'
        $sendLog.Add([PSCustomObject]@{
            Timestamp    = $timestamp
            Level        = $rowLevel
            ManagerEmail = $managerEmail
            ManagerName  = $managerName
            HtmlFile     = $htmlFile
            Status       = 'Failed'
            Error        = $errorMsg
        })
        $failedCount++
    }
}

#endregion

#region Step 8: Write send log

$sendLogPath = Join-Path $baseDir '_send-log.csv'
try {
    $sendLog | Export-Csv -LiteralPath $sendLogPath -NoTypeInformation -Encoding UTF8 -Append
    Write-Host ''
    Write-Host "  Send log written: $sendLogPath ($($sendLog.Count) row(s))" -ForegroundColor DarkGray
}
catch {
    Write-Host "  WARNING: Failed to write send log: $($_.Exception.Message)" -ForegroundColor Yellow
}

#endregion

#region Summary

Write-Host ''
Write-Host '  Escalation Mailer Complete' -ForegroundColor Cyan
Write-Host "  $('=' * 50)" -ForegroundColor DarkGray
Write-Host "  Sent:    $sentCount" -ForegroundColor Green
if ($failedCount -gt 0) {
    Write-Host "  Failed:  $failedCount" -ForegroundColor Red
}
else {
    Write-Host "  Failed:  $failedCount" -ForegroundColor Green
}
if ($skippedCount -gt 0) {
    Write-Host "  Skipped: $skippedCount" -ForegroundColor Yellow
}
Write-Host "  Total:   $($sendLog.Count)" -ForegroundColor DarkGray
Write-Host "  Subject: $emailSubject" -ForegroundColor DarkGray
Write-Host "  Server:  $($effectiveSmtpServer):$($effectiveSmtpPort)" -ForegroundColor DarkGray
Write-Host ''

Write-SPLog -Message "Invoke-SPEscalationMailer completed: sent=$sentCount failed=$failedCount skipped=$skippedCount" `
    -Severity INFO -Component 'Invoke-SPEscalationMailer' -Action 'Complete'

if ($failedCount -gt 0) {
    exit 1
}

exit 0

#endregion
